rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "9002:15672"
    - "5672:5672"
api:
  build: api/.
  env_file: .env
  links:
    - rabbitmq
  ports:
    - "1337:1337"
worker:
  build: worker/.
  env_file: .env
  links:
    - rabbitmq
